version: '3.9'

services:
  # Mongodb service
  mongo_db:
    container_name: database_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  # Node api service
  reddit-clone:
    build: .
    ports:
      # local->container
      - 4000:4000
    environment:
      PORT: 4000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: sample-db
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
