version: '3.9'

services:
  mongo_db:
    container_name: database_containers
    image: mongo:latest
    restart: always
    volumes:
      - mongo_data:/data/db

  reddit-clone:
    build: .
    ports:
      - 4400:4400
    environment:
      PORT: 4400
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: sample-db
    depends_on:
      - mongo_db

volumes:
  mongo_data: {}
